[package]
name = "rust_test1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.2.0"
async-std = "1.8.0"
csv = "1.1"
encoding_rs = "0.8.26"